services:
  - type: web
    name: efotball-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /health
